version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: nibble_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    platform: linux/amd64

  postgres_test:
    image: postgres:15
    container_name: nibble_postgres_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER_TEST} -d ${DB_NAME_TEST}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
    ports:
      - "${DB_PORT_TEST}:5432"
    volumes:
      - db_data_test:/var/lib/postgresql/data
    platform: linux/amd64

  migrate:
    image: golang:1.22.0-alpine
    container_name: nibble_migrate
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
    command: ["go", "run", "cmd/migrate/main.go", "up"]
    env_file:
      - .env

  app:
    build: .
    container_name: nibble_app
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  db_data:
  db_data_test:
